export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const LOAD_USER_DATA_PENDING = 'LOAD_USER_DATA_PENDING';
export const LOAD_USER_DATA_FULFILLED = 'LOAD_USER_DATA_FULFILLED';
export const LOAD_STREAM_DATA_PENDING = 'LOAD_STREAM_DATA_PENDING';
export const LOAD_STREAM_DATA_FULFILLED = 'LOAD_STREAM_DATA_FULFILLED';
export const LOAD_READY = 'LOAD_READY';
