export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const LOAD_STREAMS_DATA_PENDING = 'LOAD_STREAMS_DATA_PENDING';
export const LOAD_STREAMS_DATA_FULFILLED = 'LOAD_STREAMS_DATA_FULFILLED';
export const LOAD_STREAMS_DATA = 'LOAD_STREAMS_DATA';

export const SHOW_ALL = 'SHOW_ALL';
export const SHOW_ONLINE = 'SHOW_ONLINE';
export const SHOW_OFFLINE = 'SHOW_OFFLINE';
